### ISSUE TITLE
Remove link

### ISSUE THREAD

**Issue by luizboaretto** [riasvdv/statamic-linkit#11]
After creating a link with LinkIt, I can't remove the link. Have an option to enable this?

**Comment by riasvdv** [comment]
You should be able to just click this "x" and save the entry, which will result in the link being removed

![image](https://user-images.githubusercontent.com/3626559/90653593-ac509280-e23f-11ea-9dba-1b25d57badb8.png)

**Comment by JoeLimewire** [comment]
Looks as though with Statamic 6+, the 'x' is no longer there. I've had to create an override of the vue component to register a 'no link' value as a work around.

<img width="775" height="327" alt="Image" src="https://github.com/user-attachments/assets/c7d57a25-d3a2-4d5e-9f1a-ef9591c9a935" />

<img width="316" height="89" alt="Image" src="https://github.com/user-attachments/assets/63b35ff0-4743-47b0-a058-02fae1f49337" />
