### ISSUE TITLE
Add class name to link tag

### ISSUE THREAD

**Issue by mgtcampbell** [riasvdv/statamic-linkit#12]
Hi there,

First off, love the add on - thanks for creating it.

My questions is how do I add a class to the link tag - i.e. I want to use the `{{ link | linkIt }}` tag to generate the appropriate type of link based on the one chosen by the content editor (i.e. url vs tel vs email), but I would like the output to have `class="button"` on the anchor.

I've tried a few different syntaxes and plenty of google searching for how to handle this in antlers in general, but have had no luck.

Cheers
Mark

**Comment by riasvdv** [comment]
This is currently not possible, though it shouldn't be too hard to add.

**Comment by riasvdv** [comment]
Added in 1.1.0

**Comment by mgtcampbell** [comment]
Thanks so much!
