### ISSUE TITLE
Error on live site

### ISSUE THREAD

**Issue by MikeHarrison** [riasvdv/statamic-linkit#15]
Hi,

I have a Statamic site running locally using LinkIt with no problems. I have just pushed the site to the live server and am getting this error when visiting the site domain:

<img width="996" alt="Screenshot 2019-12-11 at 12 50 35" src="https://user-images.githubusercontent.com/6464063/70623155-66a1eb80-1c15-11ea-84cf-d8f4ee01b8f9.png">

Can you offer any advice why this could be happening?

Thanks!

**Comment by riasvdv** [comment]
What PHP version is your live environment running on?

**Comment by MikeHarrison** [comment]
Thanks for quick reply - the home directory is 5.6 but the domain looks like it is set to 7.2, which is what I have been using locally

**Comment by riasvdv** [comment]
The null coalescing operator (??) is a PHP 7 feature, so it seems Statamic isn't running on 7.2

**Comment by MikeHarrison** [comment]
Cool, that's great and something I can sort. Thanks for the help, and the great addon!

**Comment by MikeHarrison** [comment]
Ah ok done that and am now getting another error:

```

Whoops, looks like something went wrong.
1/1 FatalThrowableError in LinkItModifier.php line 138: Call to a member function locale() on null

    in LinkItModifier.php line 138
```

**Comment by riasvdv** [comment]
Do you have the latest version of LinkIt installed? I should have fixed that error in the latest release

**Comment by MikeHarrison** [comment]
Ah possibly not - how can I update?

**Comment by MikeHarrison** [comment]
Ah ok I was on 1.0.5 and am now on 1.1.1 - will give it a try

**Comment by MikeHarrison** [comment]
Yes that update worked, thank you
