### ISSUE TITLE
(V3) Page ID is shown instead of page title

### ISSUE THREAD

**Issue by JoeriE** [riasvdv/statamic-linkit#19]
Hi,

I'm using the plugin in Statamic v3, when I select an entry the ID is shown in the field. It would be nicer to see the actual page title.

![Linkit](https://i.ibb.co/JjmkFtc/Screenshot-2020-04-13-at-10-04-26.png)

Cheers,
Joeri

**Comment by ReneWeCode** [comment]
Agree! Confirming this in beta-44. If you reload the page, the title will be displayed correctly.

**Comment by riasvdv** [comment]
Fixed in 2.1.0!
