### ISSUE TITLE
If only one option is available the dropdown is overkill

### ISSUE THREAD

**Issue by ReneWeCode** [riasvdv/statamic-linkit#24]
If only one type is available, let's say 'entry', and only one collection is available, it's unnecessary to have a dropdown selector just to be able to select that one single option.

![Skærmbillede 2020-08-19 kl  15 41 25](https://user-images.githubusercontent.com/43215436/90642655-f54e1a00-e232-11ea-9fa7-0b43e6d94adc.png)

The clear function would also be unnecessary then.

![Skærmbillede 2020-08-19 kl  15 51 50](https://user-images.githubusercontent.com/43215436/90643514-fa5f9900-e233-11ea-9dde-f79c121be797.png)

**Comment by riasvdv** [comment]
Fixed in 2.1.0!
