### ISSUE TITLE
Modifier [linkIt] not found

### ISSUE THREAD

**Issue by Oleafeon** [riasvdv/statamic-linkit#27]
when i implement the html i get this error 
![image](https://user-images.githubusercontent.com/20043831/91043248-906c3880-e613-11ea-9ce0-4672075eed21.png)

here is my button component
`<a href="{{ button | linkIt:url }}" target="{{ button | linkIt:target }}" class="{{ classes }}">{{ button | linkIt:text }}</a>`

**Comment by riasvdv** [comment]
Hmm, does it work if you use `link_it` instead?

**Comment by Oleafeon** [comment]
i get the same error but this time with link_it
`Modifier [link_it] not found`

**Comment by riasvdv** [comment]
Did it install correctly? Can you do a `composer require rias/statamic-link-it` and copy/paste the output?

**Comment by Oleafeon** [comment]
![image](https://user-images.githubusercontent.com/20043831/91044183-2785c000-e615-11ea-9fb5-48ecbcc7d5cd.png)

**Comment by riasvdv** [comment]
Looks like composer is running out of memory before it can install

**Comment by Oleafeon** [comment]
even if i set it on memory-limit=-1 it runs out of memory

**Comment by Oleafeon** [comment]
i fixed it for composer require

i get this
![image](https://user-images.githubusercontent.com/20043831/91045232-db3b7f80-e616-11ea-8ff6-ec55caccbca2.png)

**Comment by riasvdv** [comment]
Ok, I've found the issue, should be fixed when installing v2.1.2

**Comment by Oleafeon** [comment]
allright
