### ISSUE TITLE
collection not returning all entries of one collection

### ISSUE THREAD

**Issue by Oleafeon** [riasvdv/statamic-linkit#30]
Hi i have a problem that when i put the type on a collection it does not give all entries in that collection. P.S. i am working with a multi language site and it gives me entries double
![image](https://user-images.githubusercontent.com/20043831/97412227-90cdcc00-1901-11eb-9ad9-7c486b085423.png)

**Comment by riasvdv** [comment]
If you search for a specific entry that is missing, does it load then? The multiple entries is indeed an issue, it was recently solved in Statamic core and I can now fix this in LinkIt as well, will do soon!

**Comment by Oleafeon** [comment]
searching for that entry does not work either

**Comment by riasvdv** [comment]
So I've tested in a new install and entries shouldn't be duplicated anymore if you're on the latest Statamic version.

As for not all entries showing up, could you test this again in the latest version of Statamic? I have over 500 entries and they're all showing up in the dropdown

**Comment by Oleafeon** [comment]
Yes now it works fine thank you
