### ISSUE TITLE
Entries dropdown only loads on second try

### ISSUE THREAD

**Issue by juresrpcic** [riasvdv/statamic-linkit#31]
I've got a Linkit field that's linked to a Fieldset (not added directly to blueprint).

When I select an Entry, nothing shows up (no dropdown with available Entries) - but if I clear the dropdown and select Entry again, it does load (Network tab shows two XHR requests on second select - `field-meta` and `relationship` endpoints).

This happens if added directly to a Collection or if linked deeper (inside a nested Replicator).

Nothing shows up in Console that would help.

Here's a GIF demonstration:

![linkit-issue](https://user-images.githubusercontent.com/2803433/110466008-6e309880-80d5-11eb-9835-360a078ed40a.gif)

Everything is using the latest versions - here are all my current addons:

![image](https://user-images.githubusercontent.com/2803433/110466086-8b656700-80d5-11eb-8370-1f2db19b54be.png)

**Comment by riasvdv** [comment]
Small bug that was introduced in the previous release, should be fixed now!

**Comment by juresrpcic** [comment]
Thanks Rias - tested and it works. 👏
