### ISSUE TITLE
mailto and tel not set on link

### ISSUE THREAD

**Issue by Oleafeon** [riasvdv/statamic-linkit#33]
Whenever i put the link on tel, it places the cellphone number without tel: infront of it.
Same for mailto

cp:
![image](https://user-images.githubusercontent.com/20043831/127468361-96f0725b-e4f8-42a0-8a56-62accd1c8817.png)

frontend:
![image](https://user-images.githubusercontent.com/20043831/127468435-2a4d0c45-3cb3-4445-82f2-1901bf852363.png)

Idk if you did this on purpose.
For now ill place tel: in the cp

**Comment by riasvdv** [comment]
How are you using the fieldtype in Antlers/Blade?

**Comment by Oleafeon** [comment]
i am writing it like this
![image](https://user-images.githubusercontent.com/20043831/127740849-8fd7ad09-b86b-491d-b131-b991403886ae.png)

**Comment by Oleafeon** [comment]
do you have a clue why this is happening?

**Comment by riasvdv** [comment]
You should output `{{ button | linkIt:prefix }}` before the url to get the prefix for the url as well. It seems like the documentation for this is missing, I'll update that soon
