### ISSUE TITLE
Could not find files to load the `linkit` modifier

### ISSUE THREAD

**Issue by bhashkar007** [riasvdv/statamic-linkit#4]
I am facing a strange error. The LinkIt tag is working on home page only and for all inner pages, its throwing error "Could not find files to load the `linkit` modifier". Please see in screenshot. 
![Screenshot 2019-06-18 at 8 33 59 AM](https://user-images.githubusercontent.com/1473647/59650796-f5710680-91a4-11e9-9c36-13bdf06f0b01.png)

**Comment by riasvdv** [comment]
Hi @bhashkar007 please verify you are using `linkIt` (with a capital "i" for It) or `link-it` as the modifier.

**Comment by bhashkar007** [comment]
Thanks, it fixed the problem.
