### ISSUE TITLE
the dropdown has the wrong z-index

### ISSUE THREAD

**Issue by Oleafeon** [riasvdv/statamic-linkit#40]
![image](https://github.com/riasvdv/statamic-linkit/assets/20043831/b5694c95-c4a7-4678-8fd2-4c767dabb6bc)

**Comment by Oleafeon** [comment]
@riasvdv do you have an idea?

**Comment by sattyframework** [comment]
Has there been a fix for this yet, as I am also getting this bug too. I am on the latest version. Also I have only noticed this issue since upgrading to statamic 4

**Comment by DwainsWorld** [comment]
Likewise @riasvdv - only since upgrading to Statamic 4 has this became an issue. Quite a showstopper for our clients.

**Comment by DwainsWorld** [comment]
Issue resolved by #41

**Comment by riasvdv** [comment]
I've released v2.3.1 which should solve the issue thanks to @DwainsWorld could you double check that it's now fixed?

**Comment by DwainsWorld** [comment]
Ran the following, everything looking good on my end:

1. `composer update` 
2. `php artisan vendor:publish --provider="Rias\LinkIt\ServiceProvider" --force` (overwrite existing dist assets)

**Comment by Oleafeon** [comment]
I have tested this and this has been fixed in the latest update thank you all
