### ISSUE TITLE
LinkIt does not support localization

### ISSUE THREAD

**Issue by felixtosh** [riasvdv/statamic-linkit#6]
When I link to an entry in my website and switch the language to German (/de/), the URL doesn't switch to the locale version of the same object (I have a translated version). Any ways to implement this @riasvdv ?

**Comment by riasvdv** [comment]
Currently LinkIt does not take the locale into account, I'll get this fixed asap

**Comment by riasvdv** [comment]
1.0.6 should fix this. Let me know if you encounter any more issues
