### ISSUE TITLE
Linkit in Bard-Text

### ISSUE THREAD

**Issue by HellPat** [riasvdv/statamic-linkit#8]
Hey there, I love the plugin.
Theres just one missing piece in the puzzle.

Is it possible to use the plugin to link Text inside of a bard editor?
I don't want my users to type in links by their own because thats too error prone.

**Comment by riasvdv** [comment]
This **should** technically be possible, though currently I don't see it worth the time investment, as Statamic v3 will replace the current Bard implementation with a different one https://v3.statamic.com/blog/bard-reimagined-again

Once I know how it should be implemented there, I might be able to work on a feature like this.

**Comment by HellPat** [comment]
Ah, thanks for the good hint

**Comment by ReneWeCode** [comment]
@riasvdv Actual it would be awesome to be able to use your addon in the bard instead of the build-in inline link feature. 
Do you have a plan to implement this?

**Comment by riasvdv** [comment]
I've researched this again and it's not really feasible to do in a Bard plugin for me
